version: "3.5"
services:
  drss-mongo:
    container_name: drss-mongodb-container
    restart: on-failure:5
    command: mongod --port 27017
    # Uncomment below to hide mongo logs
    # logging:
    #   driver: none
    image: mongo:latest
    volumes:
      - 'db-data:/data/db'
    networks:
      - drss-network
  drss-bot:
    container_name: drss-bot-container
    restart: on-failure:10
    build: .
    networks:
      - drss-network
    environment:
      - DRSS_BOT_TOKEN=drss_docker_token
      - DRSS_DATABASE_URI=mongodb://drss-mongo:27017/rss

volumes:
  db-data:

networks:
  drss-network:
    name: drss-network
